### ISSUE TITLE
Notifications

### ISSUE THREAD

**Issue by boutell** [punkave/apostrophe-workflow#33]
Port 0.5 notifications to the 2.x core. These are used in situations where we might otherwise have been stuck calling alert(). confirm() is a separate concern.

Then replace all the alerts in the workflow module and introduce more.

Person-to-person notifications are further down the timeline. There are bigger questions there, like whether every single person who has the right to commit something is appropriate to nag.

**Comment by agilbert** [comment]
@boutell I am working on this but am running into an issue with using `pushAsset` to render a template.

Here is my code:

```// This module provides a framework for triggering notifications within the Apostrophe admin UI.

module.exports = {
  extend: 'apostrophe-module',

  afterConstruct: function(self) {
    self.pushAsset('template', 'notification', { when: 'user' });
    self.pushAsset('template', 'notificationsContainer', { when: 'user' });
  }
};
```

The error I'm getting is `TypeError: Cannot read property 'call' of undefined` (full stack trace below). Is there something obviously wrong with this module configuration?

```
TypeError: Cannot read property 'call' of undefined
    at Object.self.renderTemplateAsset (/Users/alex/Code/apostrophe/lib/modules/apostrophe-assets/index.js:1167:16)
    at /Users/alex/Code/apostrophe/lib/modules/apostrophe-assets/index.js:1437:23
    at arrayMap (/Users/alex/Code/apostrophe/node_modules/lodash/index.js:1406:25)
    at Function.map (/Users/alex/Code/apostrophe/node_modules/lodash/index.js:6710:14)
    at Object.self.addHelpers.templates (/Users/alex/Code/apostrophe/lib/modules/apostrophe-assets/index.js:1436:43)
    at Object.object.(anonymous function) [as templates] (/Users/alex/Code/apostrophe/lib/modules/apostrophe-templates/index.js:112:30)
    at null.<anonymous> (/Users/alex/Code/apostrophe/node_modules/nunjucks/src/runtime.js:232:29)
    at Object.callWrap (/Users/alex/Code/apostrophe/node_modules/nunjucks/src/runtime.js:248:16)
    at eval (eval at <anonymous> (/Users/alex/Code/apostrophe/node_modules/nunjucks/src/environment.js:564:24), <anonymous>:56:67)
    at b_afterMain (eval at <anonymous> (/Users/alex/Code/apostrophe/node_modules/nunjucks/src/environment.js:564:24), <anonymous>:165:1)
    at eval (eval at <anonymous> (/Users/alex/Code/apostrophe/node_modules/nunjucks/src/environment.js:564:24), <anonymous>:52:88)
    at eval (eval at <anonymous> (/Users/alex/Code/apostrophe/node_modules/nunjucks/src/environment.js:564:24), <anonymous>:79:1)
    at eval (eval at <anonymous> (/Users/alex/Code/apostrophe/node_modules/nunjucks/src/environment.js:564:24), <anonymous>:142:1)
    at b_forgot (eval at <anonymous> (/Users/alex/Code/apostrophe/node_modules/nunjucks/src/environment.js:564:24), <anonymous>:234:1)
    at eval (eval at <anonymous> (/Users/alex/Code/apostrophe/node_modules/nunjucks/src/environment.js:564:24), <anonymous>:138:27)
    at b_buttonLabel (eval at <anonymous> (/Users/alex/Code/apostrophe/node_modules/nunjucks/src/environment.js:564:24), <anonymous>:213:1)```

**Comment by boutell** [comment]
Pushing templates is pretty much defunct in favor of server side rendering
via ajax. Would not be at all surprised if it didn't even work due to some
bit of bitrot. Not the simple answer you wanted...

Talk to me tomorrow about 2.x patterns for this.

**Comment by agilbert** [comment]
Other notes from @boutell:

> Re #33, there is currently exactly one DOM template in Apostrophe 2.x. It’s in the area editor. And it doesn’t use pushAsset. Instead, `editor.html` is rendered by a POST route any time an area editor is actually wanted, and that includes the bit of markup that gets reused as a template.
> 
> ```  // Supplies static DOM templates to the editor on request
>   self.route('post', 'editor', function(req, res) {
>     return res.send(self.render(req, 'editor'));
>   });
> ```
> 
> Following that pattern, the notifications module’s `user.js` could hit back to a route to get a template. But I think it would be better to do something like registering the possible notifications on the server side and rendering them there, so things like `__()` can happen for localization. Which is, um, relevant for this project.
> 
> in that scheme, the browser would hit a route with a notification name and maybe some parameters, which would get sanitized to be definitely strings for safety, and the server would render nicely with `__('Hey, you forgot to eat your %s', argument)` in the appropriate template

**Comment by boutell** [comment]
We now have notifications rather than alerts throughout the workflow module, and many new notifications for common scenarios.
